#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")
#@ load("@ytt:library", "library")
#@ load("@ytt:assert", "assert")
#@ load("validations.star", "value")
#@ load("networking.lib.yml", "networking")

#! -- DB --

#@ cc_db_user = data.values.cc.db.username or "cc-db"
#@ uaa_db_user = data.values.uaa.db.username or "uaa-db"

#@ def db_values():
databases:
#@overlay/append
- name: cc
  username: #@ cc_db_user
  password: #@ data.values.cc.db.password
#@overlay/append
- name: uaa
  username: #@ uaa_db_user
  password: #@ data.values.uaa.db.password
#@ end

#@ if data.values.db.enabled:
#@   db = library.get("github.com/cloudfoundry/db/config").with_data_values(db_values())
#@   db_url = db.export("url")()
#@ end

#@ cc_db_url = data.values.cc.db.url or db_url
#@ uaa_db_url = data.values.uaa.db.url or db_url

#! -- UAA basics --

#@ def uaa_values():
db:
  url: #@ uaa_db_url
  username: #@ uaa_db_user
  password: #@ data.values.uaa.db.password
#@ end

#@ uaa = library.get("github.com/cloudfoundry/uaa/config").with_data_values(uaa_values())
#@ uaa_url = uaa.export("url")()

#! -- CC --

#@ def cc_values():
uaa:
  url: #@ uaa_url
  client_secret: #@ data.values.cc.uaa_client_secret
db:
  url: #@ cc_db_url
  username: #@ cc_db_user
  password: #@ data.values.cc.db.password
#@ end

#@ cc = library.get("github.com/cloudfoundry/cc/config").with_data_values(cc_values())

#! -- Networking --

#@ net = networking(cc_url=cc.export("url")(), uaa_url=uaa_url)

#! -- UAA additional config --

#@ def uaa_clients_values():
clients:
#@overlay/append
- name: #@ cc.export("uaa_client")()
  secret: #@ data.values.cc.uaa_client_secret
#@overlay/append
- name: #@ data.values.networking.uaa_client
  secret: #@ data.values.networking.uaa_client_secret
#@ end

#@ uaa = uaa.with_data_values(uaa_clients_values())

--- #@ template.replace(cc.eval())
--- #@ template.replace(uaa.eval())
--- #@ template.replace(net.eval())

#@ if/end data.values.db.enabled:
--- #@ template.replace(db.eval())
